/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SnippetGroup = {
  _type: "snippetGroup";
  title?: string;
  snippets: Array<
    {
      _key: string;
    } & Snippet
  >;
};

export type Snippet = {
  _type: "snippet";
  filename: string;
  source?: string;
  code: Code;
  annotations?: Array<{
    id: string;
    kind: "decision" | "context";
    match: string;
    occurrence?: number;
    body: string;
    _type: "codeAnnotation";
    _key: string;
  }>;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h1" | "h2" | "h3" | "h4" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
      _key: string;
    }
  | ({
      _key: string;
    } & Snippet)
  | ({
      _key: string;
    } & SnippetGroup)
>;

export type ProjectImage = {
  _type: "projectImage";
  index: number;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Company = {
  _type: "company";
  name: string;
  label?: string;
  href?: string;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Duration = {
  _type: "duration";
  from: string;
  to?: string;
};

export type ExperienceReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "experience";
};

export type ProjectReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "project";
};

export type Cv = {
  _id: string;
  _type: "cv";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  summary: string;
  experience: Array<
    {
      _key: string;
    } & ExperienceReference
  >;
  projects?: Array<
    {
      _key: string;
    } & ProjectReference
  >;
  education?: {
    degree: string;
    place: string;
    detail?: string;
  };
  skillGroups?: Array<{
    label: string;
    items: string;
    _type: "skillGroup";
    _key: string;
  }>;
};

export type Tool = {
  _id: string;
  _type: "tool";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  href?: string;
  iconSource: "react-icons" | "custom";
  iconName?: string;
  iconSvg?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Metadata = {
  _id: string;
  _type: "metadata";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  slug: Slug;
  title: string;
  description: string;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type ToolReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "tool";
};

export type Experience = {
  _id: string;
  _type: "experience";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  location: string;
  duration: Duration;
  company: Company;
  tools?: Array<
    {
      _key: string;
    } & ToolReference
  >;
  cvBullets?: Array<string>;
};

export type ProjectKindReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "projectKind";
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug?: Slug;
  featured?: boolean;
  date: string;
  kind: ProjectKindReference;
  status: "completed" | "ongoing" | "paused";
  description: string;
  href?: string;
  source?: string;
  tools: Array<
    {
      _key: string;
    } & ToolReference
  >;
  images?: Array<
    {
      _key: string;
    } & ProjectImage
  >;
  cvBlurb?: string;
  contentTitle?: string;
  content?: BlockContent;
};

export type ProjectKind = {
  _id: string;
  _type: "projectKind";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
};

export type AboutMe = {
  _id: string;
  _type: "aboutMe";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  role?: string;
  bio: BlockContent;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  heroLabel: string;
  heroHeadline: string;
  heroDescription: string;
  currentStatusLabel: string;
  currentStatus: string;
};

export type Code = {
  _type: "code";
  language?: string;
  filename?: string;
  code?: string;
  highlightedLines?: Array<number>;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SnippetGroup
  | Snippet
  | SanityImageAssetReference
  | BlockContent
  | ProjectImage
  | Company
  | Duration
  | ExperienceReference
  | ProjectReference
  | Cv
  | Tool
  | SanityImageCrop
  | SanityImageHotspot
  | Metadata
  | Slug
  | ToolReference
  | Experience
  | ProjectKindReference
  | Project
  | ProjectKind
  | AboutMe
  | Code
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../web/src/lib/sanity/queries.ts
// Variable: getAboutMe
// Query: *[_type == "aboutMe"]{  name,  role,  bio,  "imageUrl": image.asset->url,  heroLabel,  heroHeadline,  heroDescription,  currentStatusLabel,  currentStatus}[0]
export type GetAboutMeResult = {
  name: string;
  role: string | null;
  bio: BlockContent;
  imageUrl: string | null;
  heroLabel: string;
  heroHeadline: string;
  heroDescription: string;
  currentStatusLabel: string;
  currentStatus: string;
} | null;

// Source: ../web/src/lib/sanity/queries.ts
// Variable: getCv
// Query: *[_id in ["cv", "drafts.cv"]] | order(_id asc)[0]{  summary,  experience[]->{    title,    location,    duration,    company{name, label, href},    tools[]->{name},    cvBullets  },  projects[]->{    title,    tools[]->{name},    date,    status,    href,    source,    cvBlurb  },  education,  skillGroups}
export type GetCvResult =
  | {
      summary: null;
      experience: null;
      projects: null;
      education: null;
      skillGroups: null;
    }
  | {
      summary: string;
      experience: Array<{
        title: string;
        location: string;
        duration: Duration;
        company: {
          name: string;
          label: string | null;
          href: string | null;
        };
        tools: Array<{
          name: string;
        }> | null;
        cvBullets: Array<string> | null;
      }>;
      projects: Array<{
        title: string;
        tools: Array<{
          name: string;
        }>;
        date: string;
        status: "completed" | "ongoing" | "paused";
        href: string | null;
        source: string | null;
        cvBlurb: string | null;
      }> | null;
      education: {
        degree: string;
        place: string;
        detail?: string;
      } | null;
      skillGroups: Array<{
        label: string;
        items: string;
        _type: "skillGroup";
        _key: string;
      }> | null;
    }
  | null;

// Source: ../web/src/lib/sanity/queries.ts
// Variable: getFeaturedProjects
// Query: *[_type == "project" && featured == true] | order(date desc)[0..3]{  title,  slug,  featured,  date,  status,  description,  href,  source,  tools[]->{   name,    href,    iconSource,    iconName,    "iconSvg": iconSvg.asset->url  },   "mainImage": images[0].image.asset->url}
export type GetFeaturedProjectsResult = Array<{
  title: string;
  slug: Slug | null;
  featured: true;
  date: string;
  status: "completed" | "ongoing" | "paused";
  description: string;
  href: string | null;
  source: string | null;
  tools: Array<{
    name: string;
    href: string | null;
    iconSource: "custom" | "react-icons";
    iconName: string | null;
    iconSvg: string | null;
  }>;
  mainImage: string | null;
}>;

// Source: ../web/src/lib/sanity/queries.ts
// Variable: getProjectBySlug
// Query: *[_type == "project" && slug.current == $slug]{  title,  slug,  date,  status,  description,  href,  source,  tools[]->{    name,    href,    iconSource,    iconName,    "iconSvg": iconSvg.asset->url  },  "images": images[].image.asset->url,  contentTitle,  content[]{    ...,    _type == "image" => {      "altText": asset->altText    }  },}[0]
export type GetProjectBySlugResult = {
  title: string;
  slug: Slug | null;
  date: string;
  status: "completed" | "ongoing" | "paused";
  description: string;
  href: string | null;
  source: string | null;
  tools: Array<{
    name: string;
    href: string | null;
    iconSource: "custom" | "react-icons";
    iconName: string | null;
    iconSvg: string | null;
  }>;
  images: Array<string | null> | null;
  contentTitle: string | null;
  content: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
        altText: string | null;
      }
    | {
        _key: string;
        _type: "snippet";
        filename: string;
        source?: string;
        code: Code;
        annotations?: Array<{
          id: string;
          kind: "context" | "decision";
          match: string;
          occurrence?: number;
          body: string;
          _type: "codeAnnotation";
          _key: string;
        }>;
      }
    | {
        _key: string;
        _type: "snippetGroup";
        title?: string;
        snippets: Array<
          {
            _key: string;
          } & Snippet
        >;
      }
  > | null;
} | null;

// Source: ../web/src/lib/sanity/queries.ts
// Variable: getProjectMetadata
// Query: *[_type == "project" && slug.current == $slug]{  title,  slug,  description,  "images": images[0].image.asset->url,  contentTitle,}[0]
export type GetProjectMetadataResult = {
  title: string;
  slug: Slug | null;
  description: string;
  images: string | null;
  contentTitle: string | null;
} | null;

// Source: ../web/src/lib/sanity/queries.ts
// Variable: getProjectsForSEO
// Query: *[_type == "project"]{  "slug": slug.current,  "publishedAt": date,}
export type GetProjectsForSEOResult = Array<{
  slug: string | null;
  publishedAt: string;
}>;

// Source: ../web/src/lib/sanity/queries.ts
// Variable: getMetadata
// Query: *[_type == "metadata" && slug.current == $slug]{  "slug": slug.current,  title,  description,}[0]
export type GetMetadataResult = {
  slug: string;
  title: string;
  description: string;
} | null;

// Source: ../web/src/lib/sanity/queries.ts
// Variable: getProjects
// Query: *[_type == "project"]{  title,  slug,  featured,  date,  status,  "kind": kind->title,  description,  href,  source,  tools[]->{    name,    href,    iconSource,    iconName,    "iconSvg": iconSvg.asset->url  },   "mainImage": images[0].image.asset->url} | order(date desc)
export type GetProjectsResult = Array<{
  title: string;
  slug: Slug | null;
  featured: boolean | null;
  date: string;
  status: "completed" | "ongoing" | "paused";
  kind: string;
  description: string;
  href: string | null;
  source: string | null;
  tools: Array<{
    name: string;
    href: string | null;
    iconSource: "custom" | "react-icons";
    iconName: string | null;
    iconSvg: string | null;
  }>;
  mainImage: string | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "aboutMe"]{\n  name,\n  role,\n  bio,\n  "imageUrl": image.asset->url,\n  heroLabel,\n  heroHeadline,\n  heroDescription,\n  currentStatusLabel,\n  currentStatus\n}[0]': GetAboutMeResult;
    '*[_id in ["cv", "drafts.cv"]] | order(_id asc)[0]{\n  summary,\n  experience[]->{\n    title,\n    location,\n    duration,\n    company{name, label, href},\n    tools[]->{name},\n    cvBullets\n  },\n  projects[]->{\n    title,\n    tools[]->{name},\n    date,\n    status,\n    href,\n    source,\n    cvBlurb\n  },\n  education,\n  skillGroups\n}': GetCvResult;
    '*[_type == "project" && featured == true] | order(date desc)[0..3]{\n  title,\n  slug,\n  featured,\n  date,\n  status,\n  description,\n  href,\n  source,\n  tools[]->{\n   name,\n    href,\n    iconSource,\n    iconName,\n    "iconSvg": iconSvg.asset->url\n  },\n   "mainImage": images[0].image.asset->url\n}': GetFeaturedProjectsResult;
    '*[_type == "project" && slug.current == $slug]{\n  title,\n  slug,\n  date,\n  status,\n  description,\n  href,\n  source,\n  tools[]->{\n    name,\n    href,\n    iconSource,\n    iconName,\n    "iconSvg": iconSvg.asset->url\n  },\n  "images": images[].image.asset->url,\n  contentTitle,\n  content[]{\n    ...,\n    _type == "image" => {\n      "altText": asset->altText\n    }\n  },\n}[0]': GetProjectBySlugResult;
    '*[_type == "project" && slug.current == $slug]{\n  title,\n  slug,\n  description,\n  "images": images[0].image.asset->url,\n  contentTitle,\n}[0]': GetProjectMetadataResult;
    '*[_type == "project"]{\n  "slug": slug.current,\n  "publishedAt": date,\n}': GetProjectsForSEOResult;
    '*[_type == "metadata" && slug.current == $slug]{\n  "slug": slug.current,\n  title,\n  description,\n}[0]': GetMetadataResult;
    '*[_type == "project"]{\n  title,\n  slug,\n  featured,\n  date,\n  status,\n  "kind": kind->title,\n  description,\n  href,\n  source,\n  tools[]->{\n    name,\n    href,\n    iconSource,\n    iconName,\n    "iconSvg": iconSvg.asset->url\n  },\n   "mainImage": images[0].image.asset->url\n} | order(date desc)': GetProjectsResult;
  }
}
