/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SnippetGroup = {
  _type: "snippetGroup";
  title?: string;
  snippets: Array<
    {
      _key: string;
    } & Snippet
  >;
};

export type Snippet = {
  _type: "snippet";
  filename: string;
  source?: string;
  code: Code;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h1" | "h2" | "h3" | "h4" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
      _key: string;
    }
  | ({
      _key: string;
    } & Snippet)
  | ({
      _key: string;
    } & SnippetGroup)
>;

export type ProjectImage = {
  _type: "projectImage";
  index: number;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Description = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "blockquote";
  listItem?: "bullet";
  markDefs?: Array<{
    href?: string;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type Company = {
  _type: "company";
  name: string;
  label: string;
  href: string;
  logo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Duration = {
  _type: "duration";
  from: string;
  to?: string;
};

export type Tool = {
  _id: string;
  _type: "tool";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  href?: string;
  iconSource: "react-icons" | "custom";
  iconName?: string;
  iconSvg?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Metadata = {
  _id: string;
  _type: "metadata";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  slug: Slug;
  title: string;
  description: string;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type ToolReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "tool";
};

export type Experience = {
  _id: string;
  _type: "experience";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  location: string;
  partTime?: boolean;
  duration: Duration;
  company: Company;
  tools?: Array<
    {
      _key: string;
    } & ToolReference
  >;
  description: Description;
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug?: Slug;
  featured?: boolean;
  date: string;
  kind: "Web app" | "Client site" | "Game" | "Android app" | "This site";
  status: "completed" | "ongoing" | "paused";
  description: string;
  href?: string;
  source?: string;
  tools: Array<
    {
      _key: string;
    } & ToolReference
  >;
  images?: Array<
    {
      _key: string;
    } & ProjectImage
  >;
  contentTitle?: string;
  content?: BlockContent;
};

export type AboutMe = {
  _id: string;
  _type: "aboutMe";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  bio: BlockContent;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  heroLabel: string;
  heroHeadline: string;
  heroDescription: string;
  currentStatusLabel: string;
  currentStatus: string;
  email: string;
  github: string;
  githubLabel: string;
  linkedin: string;
  linkedinLabel: string;
};

export type Code = {
  _type: "code";
  language?: string;
  filename?: string;
  code?: string;
  highlightedLines?: Array<number>;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SnippetGroup
  | Snippet
  | SanityImageAssetReference
  | BlockContent
  | ProjectImage
  | Description
  | Company
  | Duration
  | Tool
  | SanityImageCrop
  | SanityImageHotspot
  | Metadata
  | Slug
  | ToolReference
  | Experience
  | Project
  | AboutMe
  | Code
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../web/src/lib/sanity/queries.ts
// Variable: getAboutMe
// Query: *[_type == "aboutMe"]{  name,  bio,  "imageUrl": image.asset->url,  heroLabel,  heroHeadline,  heroDescription,  currentStatusLabel,  currentStatus,  email,  github,  githubLabel,  linkedin,  linkedinLabel}[0]
export type GetAboutMeResult = {
  name: string;
  bio: BlockContent;
  imageUrl: string | null;
  heroLabel: string;
  heroHeadline: string;
  heroDescription: string;
  currentStatusLabel: string;
  currentStatus: string;
  email: string;
  github: string;
  githubLabel: string;
  linkedin: string;
  linkedinLabel: string;
} | null;

// Source: ../web/src/lib/sanity/queries.ts
// Variable: getMainImage
// Query: *[_type == "aboutMe"]{  "imageUrl": image.asset->url,}[0]
export type GetMainImageResult = {
  imageUrl: string | null;
} | null;

// Source: ../web/src/lib/sanity/queries.ts
// Variable: getExperiences
// Query: *[_type == "experience"]{  title,  location,  partTime,  duration,  company,  description,  "logo": company.logo.asset->url,  tools[]->{    name,    href,    iconSource,    iconName,    "iconSvg": iconSvg.asset->url  },} | order(duration.from desc)
export type GetExperiencesResult = Array<{
  title: string;
  location: string;
  partTime: boolean | null;
  duration: Duration;
  company: Company;
  description: Description;
  logo: string | null;
  tools: Array<{
    name: string;
    href: string | null;
    iconSource: "custom" | "react-icons";
    iconName: string | null;
    iconSvg: string | null;
  }> | null;
}>;

// Source: ../web/src/lib/sanity/queries.ts
// Variable: getFeaturedProjects
// Query: *[_type == "project" && featured == true]{  title,  slug,  featured,  date,  status,  description,  href,  source,  tools[]->{   name,    href,    iconSource,    iconName,    "iconSvg": iconSvg.asset->url  },   "mainImage": images[0].image.asset->url}[0..3] | order(date desc)
export type GetFeaturedProjectsResult = Array<{
  title: string;
  slug: Slug | null;
  featured: true;
  date: string;
  status: "completed" | "ongoing" | "paused";
  description: string;
  href: string | null;
  source: string | null;
  tools: Array<{
    name: string;
    href: string | null;
    iconSource: "custom" | "react-icons";
    iconName: string | null;
    iconSvg: string | null;
  }>;
  mainImage: string | null;
}>;

// Source: ../web/src/lib/sanity/queries.ts
// Variable: getProjectBySlug
// Query: *[_type == "project" && slug.current == $slug]{  title,  slug,  date,  status,  description,  href,  source,  tools[]->{    name,    href,    iconSource,    iconName,    "iconSvg": iconSvg.asset->url  },  "images": images[].image.asset->url,  contentTitle,  content,}[0]
export type GetProjectBySlugResult = {
  title: string;
  slug: Slug | null;
  date: string;
  status: "completed" | "ongoing" | "paused";
  description: string;
  href: string | null;
  source: string | null;
  tools: Array<{
    name: string;
    href: string | null;
    iconSource: "custom" | "react-icons";
    iconName: string | null;
    iconSvg: string | null;
  }>;
  images: Array<string | null> | null;
  contentTitle: string | null;
  content: BlockContent | null;
} | null;

// Source: ../web/src/lib/sanity/queries.ts
// Variable: getProjectMetadata
// Query: *[_type == "project" && slug.current == $slug]{  slug,  description,  "images": images[0].image.asset->url,  contentTitle,}[0]
export type GetProjectMetadataResult = {
  slug: Slug | null;
  description: string;
  images: string | null;
  contentTitle: string | null;
} | null;

// Source: ../web/src/lib/sanity/queries.ts
// Variable: getProjectsForSEO
// Query: *[_type == "project"]{  "slug": slug.current,  "publishedAt": date,}
export type GetProjectsForSEOResult = Array<{
  slug: string | null;
  publishedAt: string;
}>;

// Source: ../web/src/lib/sanity/queries.ts
// Variable: getMetadata
// Query: *[_type == "metadata" && slug.current == $slug]{  "slug": slug.current,  title,  description,}[0]
export type GetMetadataResult = {
  slug: string;
  title: string;
  description: string;
} | null;

// Source: ../web/src/lib/sanity/queries.ts
// Variable: getProjects
// Query: *[_type == "project"]{  title,  slug,  featured,  date,  status,  kind,  description,  href,  source,  tools[]->{    name,    href,    iconSource,    iconName,    "iconSvg": iconSvg.asset->url  },   "mainImage": images[0].image.asset->url} | order(date desc)
export type GetProjectsResult = Array<{
  title: string;
  slug: Slug | null;
  featured: boolean | null;
  date: string;
  status: "completed" | "ongoing" | "paused";
  kind: "Android app" | "Client site" | "Game" | "This site" | "Web app";
  description: string;
  href: string | null;
  source: string | null;
  tools: Array<{
    name: string;
    href: string | null;
    iconSource: "custom" | "react-icons";
    iconName: string | null;
    iconSvg: string | null;
  }>;
  mainImage: string | null;
}>;

// Source: ../web/src/lib/sanity/queries.ts
// Variable: getTools
// Query: *[_type == "tool"]{  name,  href,  iconSource,  iconName,  "iconSvg": iconSvg.asset->url}
export type GetToolsResult = Array<{
  name: string;
  href: string | null;
  iconSource: "custom" | "react-icons";
  iconName: string | null;
  iconSvg: string | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "aboutMe"]{\n  name,\n  bio,\n  "imageUrl": image.asset->url,\n  heroLabel,\n  heroHeadline,\n  heroDescription,\n  currentStatusLabel,\n  currentStatus,\n  email,\n  github,\n  githubLabel,\n  linkedin,\n  linkedinLabel\n}[0]': GetAboutMeResult;
    '*[_type == "aboutMe"]{\n  "imageUrl": image.asset->url,\n}[0]': GetMainImageResult;
    '*[_type == "experience"]{\n  title,\n  location,\n  partTime,\n  duration,\n  company,\n  description,\n  "logo": company.logo.asset->url,\n  tools[]->{\n    name,\n    href,\n    iconSource,\n    iconName,\n    "iconSvg": iconSvg.asset->url\n  },\n} | order(duration.from desc)': GetExperiencesResult;
    '*[_type == "project" && featured == true]{\n  title,\n  slug,\n  featured,\n  date,\n  status,\n  description,\n  href,\n  source,\n  tools[]->{\n   name,\n    href,\n    iconSource,\n    iconName,\n    "iconSvg": iconSvg.asset->url\n  },\n   "mainImage": images[0].image.asset->url\n}[0..3] | order(date desc)': GetFeaturedProjectsResult;
    '*[_type == "project" && slug.current == $slug]{\n  title,\n  slug,\n  date,\n  status,\n  description,\n  href,\n  source,\n  tools[]->{\n    name,\n    href,\n    iconSource,\n    iconName,\n    "iconSvg": iconSvg.asset->url\n  },\n  "images": images[].image.asset->url,\n  contentTitle,\n  content,\n}[0]': GetProjectBySlugResult;
    '*[_type == "project" && slug.current == $slug]{\n  slug,\n  description,\n  "images": images[0].image.asset->url,\n  contentTitle,\n}[0]': GetProjectMetadataResult;
    '*[_type == "project"]{\n  "slug": slug.current,\n  "publishedAt": date,\n}': GetProjectsForSEOResult;
    '*[_type == "metadata" && slug.current == $slug]{\n  "slug": slug.current,\n  title,\n  description,\n}[0]': GetMetadataResult;
    '*[_type == "project"]{\n  title,\n  slug,\n  featured,\n  date,\n  status,\n  kind,\n  description,\n  href,\n  source,\n  tools[]->{\n    name,\n    href,\n    iconSource,\n    iconName,\n    "iconSvg": iconSvg.asset->url\n  },\n   "mainImage": images[0].image.asset->url\n} | order(date desc)': GetProjectsResult;
    '*[_type == "tool"]{\n  name,\n  href,\n  iconSource,\n  iconName,\n  "iconSvg": iconSvg.asset->url\n}': GetToolsResult;
  }
}
