import type { Metadata } from 'next';
import Navbar from '@/components/navbar/Navbar';
import ThemeProvider, {
  ThemeWrapper,
} from '@/components/darkThemeProvider/DarkThemeProvider';
import './globals.css';

export const metadata: Metadata = {
  title: 'Maged Faiz - Software Developer',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <ThemeProvider>
        <body>
          <ThemeWrapper>
            <Navbar />
            {children}
          </ThemeWrapper>
        </body>
      </ThemeProvider>
    </html>
  );
}
